version: "3"
services:
  velopark-snippets:
    build: ./
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - /home/julian/data/velopark:/data/velopark
    environment: 
      - MONGO_HOST=192.168.1.2
      - MONGO_PORT=27018
      - DATA_PATH=/data/velopark
      - BASE_URL=http://velopark.ilabt.imec.be/rich-snippets-generator
      - VOCAB_URL=https://velopark.ilabt.imec.be/openvelopark
      - SUPER_ADMINS=info@fietsberaad.be
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_USER=velopark.notifications@gmail.com
      - EMAIL_PASS=REPLACE_ME
      - EMAIL_FROM=Velopark <velopark.notifications@gmail.com>
      - SECRET_TOKEN=REPLACE_ME